2014-10-13 18:34:10.581 [NotebookApp] Using existing profile dir: u'/Users/sfederow/.ipython/profile_nbserver'
2014-10-13 18:34:10.591 [NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
2014-10-13 18:34:10.692 [NotebookApp] The port 8888 is already in use, trying another random port.
2014-10-13 18:34:10.692 [NotebookApp] The port 8889 is already in use, trying another random port.
2014-10-13 18:34:10.692 [NotebookApp] Serving notebooks from local directory: /Users/sfederow/ome/ome/examples
2014-10-13 18:34:10.692 [NotebookApp] 0 active kernels 
2014-10-13 18:34:10.693 [NotebookApp] The IPython Notebook is running at: https://[all ip addresses on your system]:8890/
2014-10-13 18:34:10.693 [NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
2014-10-13 19:13:48.402 [NotebookApp] Using existing profile dir: u'/Users/sfederow/.ipython/profile_nbserver'
2014-10-13 19:13:48.410 [NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
2014-10-13 19:13:48.424 [NotebookApp] The port 8888 is already in use, trying another random port.
2014-10-13 19:13:48.425 [NotebookApp] The port 8889 is already in use, trying another random port.
2014-10-13 19:13:48.425 [NotebookApp] The port 8890 is already in use, trying another random port.
2014-10-13 19:13:48.425 [NotebookApp] Serving notebooks from local directory: /Users/sfederow/ome/ome/examples
2014-10-13 19:13:48.425 [NotebookApp] 0 active kernels 
2014-10-13 19:13:48.425 [NotebookApp] The IPython Notebook is running at: https://[all ip addresses on your system]:8891/
2014-10-13 19:13:48.426 [NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
2014-10-13 19:14:21.397 [NotebookApp] CRITICAL | received signal 15, stopping
2014-10-13 19:14:21.397 [NotebookApp] Shutting down kernels
2014-10-13 19:14:28.128 [NotebookApp] CRITICAL | received signal 15, stopping
2014-10-13 19:14:28.129 [NotebookApp] Shutting down kernels
2014-10-13 19:14:38.949 [NotebookApp] Using existing profile dir: u'/Users/sfederow/.ipython/profile_nbserver'
2014-10-13 19:14:38.957 [NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
2014-10-13 19:14:38.971 [NotebookApp] The port 8888 is already in use, trying another random port.
2014-10-13 19:14:38.972 [NotebookApp] The port 8889 is already in use, trying another random port.
2014-10-13 19:14:38.972 [NotebookApp] Serving notebooks from local directory: /Users/sfederow/ome/ome/examples
2014-10-13 19:14:38.972 [NotebookApp] 0 active kernels 
2014-10-13 19:14:38.972 [NotebookApp] The IPython Notebook is running at: https://[all ip addresses on your system]:8890/
2014-10-13 19:14:38.972 [NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
INFO:tornado.access:302 GET / (70.167.74.84) 1.61ms
INFO:tornado.access:302 POST /login?next=%2F (70.167.74.84) 1.07ms
INFO:tornado.access:302 GET / (70.167.74.84) 0.58ms
2014-10-13 19:15:20.538 [NotebookApp] WARNING | Notebook /test_queries.ipynb is not trusted
2014-10-13 19:15:20.908 [NotebookApp] Kernel started: b828491d-c728-40ed-92b8-0ded1a48e39c
2014-10-13 19:15:27.403 [NotebookApp] WARNING | Notebook /test_queries.ipynb is not trusted
WARNING:tornado.general:error on read
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 601, in _handle_read
    pos = self._read_to_buffer_loop()
  File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 571, in _read_to_buffer_loop
    if self._read_to_buffer() == 0:
  File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 683, in _read_to_buffer
    chunk = self.read_from_fd()
  File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 1289, in read_from_fd
    chunk = self.socket.read(self.read_chunk_size)
  File "/usr/local/Cellar/python/2.7.7/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 165, in read
    return self._sslobj.read(len)
SSLError: [Errno 1] _ssl.c:1429: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
ERROR:tornado.general:Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/http1connection.py", line 674, in _server_request_loop
    ret = yield conn.read_response(request_delegate)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 617, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 109, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 620, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/usr/local/lib/python2.7/site-packages/tornado/http1connection.py", line 165, in _read_message
    io_loop=self.stream.io_loop)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 617, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 111, in result
    raise self._exception
SSLError: [Errno 1] _ssl.c:1429: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
INFO:tornado.access:302 GET / (70.167.74.84) 0.65ms
INFO:tornado.access:302 POST /login?next=%2F (70.167.74.84) 0.86ms
INFO:tornado.access:302 GET / (70.167.74.84) 0.69ms
2014-10-13 19:22:05.203 [NotebookApp] WARNING | Notebook /test_queries.ipynb is not trusted
2014-10-13 19:24:05.583 [NotebookApp] Saving notebook at /test_queries.ipynb
2014-10-13 19:35:25.887 [NotebookApp] Kernel restarted: b828491d-c728-40ed-92b8-0ded1a48e39c
